### ISSUE TITLE
Server names in ffmuc.net.conf which are not working properly

### ISSUE THREAD

**Issue by goligo** [freifunkMUC/ffmuc-salt-public#102]
The list of domains in ffmuc.net.conf has recently been changed. I have tested all of them, the following have issues:
```
hp.ext.ffmuc.net - no DNS entry
(www.)ffmuc.bayern - DNS points to old IP (webfrontend01)
(www.)muenchen.freifunk.net - no valid certificate 
(www.)münchen.freifunk.net - no valid certificate 
(www.)augsburg.freifunk.net - no valid certificate 
hp.freifunk-muenchen.(de|net)  - no DNS entry
```

**Comment by goligo** [comment]
https://github.com/freifunkMUC/ffmuc-salt-public/commit/0938f264054eba30dd35e28e40d5b13fec638d43

**Comment by awlx** [comment]
All *.freifunk.net should probably be moved to their own config file. As they will also need special certificate handling.

**Comment by DasSkelett** [comment]
#96 started doing that and https://github.com/DasSkelett/ffmuc-salt-public/tree/http01-cert has some fixes and improvements for it, but hte PR has been closed.

**Comment by awlx** [comment]
@DasSkelett fixed it
