### ISSUE TITLE
Remove fastd

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/ffmuc-salt-public#52]
As the title says, we should completely remove fastd from all gateways. 

At the moment fastd is still active on gateway 4 and 5 but that's not necessary anymore and just adds complexity. This should be done when someone resolves #50 and #51

**Comment by GoliathLabs** [comment]
Things are sorted out. This might be doable now.

**Comment by GoliathLabs** [comment]
@awlx what is the current status of this issue? Since both PRs have been merged, imho there is no reason for fastd to be active anymore

**Comment by awlx** [comment]
No status, someone has to actually remove it and deinstall it on the two remaining gateways which have it.

**Comment by GoliathLabs** [comment]
Okay, maybe that's something for the new admins? @lqb @ce-4 @goligo

**Comment by goligo** [comment]
@awlx Any hints about the steps to take? ;-)

I would have expected to remove the fastd role from the gateways and salt will do the magic for me. However it looks like the salt-files for fastd already have been removed several months ago.

**Comment by awlx** [comment]
@goligo removing a salt state doesn't normally remove anything from the servers if it's not setup to do so ;). So it's basically a manual cleanup on the gateways.

**Comment by goligo** [comment]
@awlx 
```
DOMAINS="freising gauting muc_cty muc_nord muc_ost muc_sued muc_west uml_nord uml_ost uml_sued uml_west welt"
for DOMAIN in $DOMAINS; do systemctl stop fastd@$DOMAIN; done
for DOMAIN in $DOMAINS; do systemctl disable fastd@$DOMAIN; done
systemctl stop system-fastd.slice
apt remove fastd
rm /etc/systemd/system/fastd@.service
```
Ausserdem habe ich die fastd-Eintraege aus dem Config-Context in der Netbox geloescht. Sieht so aus als ob die Gateways noch laufen :-D Wenn Du Zeit hast schau doch mal, ob das alles war.
