### ISSUE TITLE
Something is wrong with map.ffmuc.net - tiles don't load or are slow

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/ffmuc-salt-public#55]
When you scroll on the map the tiles load very slow or not at all.

Maybe we need to use other upstream servers:
https://github.com/freifunkMUC/ffmuc-salt-public/blob/main/nginx/domains/tiles.ffmuc.net.conf

Please investigate the issue and fix :). 
Use graylog to verify what's causing the issues or just the webserver logs on the webservers.

**Comment by GoliathLabs** [comment]
https://help.openstreetmap.org/questions/69835/loading-speed-of-tiles-is-worse-compared-to-other-tile-services/69846

**Comment by GoliathLabs** [comment]
We also might have to change to some other upstream tile servers as we did in the past already. But the comment already points out that things might be loading slow for those who aren't using the osm project's website but their API instead

**Comment by awlx** [comment]
Maybe someone wants to spin up a PR with different servers.

**Comment by awlx** [comment]
Closed via #56
