### ISSUE TITLE
Update streaming.ffmuc.net

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/ffmuc-salt-public#62]

**Comment by GoliathLabs** [comment]
@lqb @ce-4 @goligo wer fühlt sich angesprochen?

**Comment by krombel** [comment]
There is work in progress from upstream which might lead us to the situation to remove our hacks which makes it hard to maintain atm.
I expect a new release the next few days so I would wait to let it settle a bit before trying to update it.
Current development branch which might help to dig into a possible upgrade path:
https://gitlab.com/Deamos/open-streaming-platform-docker/-/tree/development/0.8.0

**Comment by krombel** [comment]
Right now the usage profile is quite low. But this does not mean it is abandoned.
Besides thinking of somehow integrating it with streaming infrastructure for https://meet.ffmuc.net to remove the YouTube-Dependency I think it is quite likely it will be used for future events (as it has happened in the past already)

**Comment by awlx** [comment]
But given the low usage, we maybe just give it a fresh start with the new docker-image without and "Gefrickel".

**Comment by GoliathLabs** [comment]
Not deployed anymore
