### ISSUE TITLE
Upgrade Graylog to latest version

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/ffmuc-salt-public#63]
<img width="1000" alt="Screenshot 2021-08-14 at 11 36 32" src="https://user-images.githubusercontent.com/6527744/129441730-03b8e79c-de87-434b-8470-7f67646d7650.png">

**Comment by GoliathLabs** [comment]
@lqb @ce-4 @goligo wer fühlt sich angesprochen?

**Comment by lqb** [comment]
Updated to 4.1.3-2
