### ISSUE TITLE
Update cfssl

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/ffmuc-salt-public#68]
current release is https://github.com/cloudflare/cfssl/releases/tag/v1.6.1
TODO: Check what is running in our infra and update it to latest release.

Note: Be careful as this tool takes care of our internal CA.

**Comment by lqb** [comment]
WHY special care? Doesn't the backup work for this?

**Comment by GoliathLabs** [comment]
Who feels like doing this task? @freifunkMUC/salt-stack
